version: "3"

services:
  logto-app:
    depends_on:
      logto-postgres:
        condition: service_healthy
    image: ghcr.io/logto-io/logto:1.0.0-beta.10
    ports:
      - 3001:3001
    environment:
      - ALL_YES=1
      - NO_INQUIRY=0
      - TRUST_PROXY_HEADER=1
      - DB_URL_DEFAULT=postgres://postgres:p0stgr3s@logto-postgres:5432
      - ENDPOINT=https://3001-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}
      # Required for sending emails to our `maildev` instance (during development)
      - NODE_TLS_REJECT_UNAUTHORIZED=0
  logto-postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
